### ISSUE TITLE
DiHT-B/32 load model fails

### ISSUE THREAD

**Issue by filipradenovic** [facebookresearch/diht#5]
When running:
```
text_tokenizer, image_transform, model = model_zoo.load_model("diht_vitb32_224px, is_train=False)
```
it fails with following error:
```
Traceback (most recent call last):
  File "/private/home/filipradenovic/diht/example_imagenet_eval.py", line 79, in <module>
    main()
  File "/private/home/filipradenovic/diht/example_imagenet_eval.py", line 27, in main
    text_tokenizer, image_transform, model = model_zoo.load_model(
  File "/private/home/filipradenovic/diht/diht/model_zoo.py", line 144, in load_model
    ckpt_path = _download_model_ckpt(
  File "/private/home/filipradenovic/diht/diht/model_zoo.py", line 78, in _download_model_ckpt
    raise RuntimeError(
RuntimeError: Model has been downloaded but the SHA256 checksum does not not match
```

**Comment by filipradenovic** [comment]
Fixed by PR #10
